name: tweet-sentiment
channels:
  - anaconda
  - pytorch
dependencies:
  - python=3.7
  - jupyter
  - pandas
  - spacy
  - pytorch
  - torchvision
  - scikit-learn
  - matplotlib
  - pip:
    - transformers